-   repo: git://github.com/pre-commit/pre-commit-hooks
    # sha: v0.4.2
    sha: 15b678e9c67c42765c3d579e40672a332f4366d7
    hooks:
    # added in v0.4.2 or 9ce45609a92f648c87b42207410386fd69a5d1e5
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
    # added in v0.4.2 or c9b6161fab48f76913ec31006ea233571f927b67
    -   id: check-merge-conflict
        # files: ^(?!git-crypt).*(?<!\.md)$
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        # args: [--maxkb=500] # default reject files >= 500KB
    -   id: check-case-conflict
    -   id: check-yaml
    # -   id: check-json
